import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Home, User, Phone } from 'lucide-react';
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
    { name: 'Home', href: '/', icon: Home },
    { name: 'Search Contact', href: '/search-contact', icon: Phone }
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html>
      <body>
      <div className="flex flex-col-reverse md:flex-col md:m-4 md:rounded-full justify-between min-h-screen bg-gradient-to-b from-gray-50 to-gray-100">
          <nav className="bg-white shadow-sm">
              <div className="mx-auto px-4 sm:px-6 lg:px-8">
                  <div className="flex justify-between h-16">
                      <div className="flex">
                          {navigation.map((item) => (
                              <Link
                                  key={item.name}
                                  href={item.href}
                                  className={`inline-flex items-center px-4 py-2 border-b-2 text-sm font-medium transition-colors duration-200 ease-in-out hover:text-primary 
                                  `}
                              >
                                  <item.icon className="h-5 w-5 mr-2" />
                                  {item.name}
                              </Link>
                          ))}
                      </div>
                  </div>
              </div>
          </nav>
          <main className=" px-4 sm:px-6 lg:px-8 py-8 animate-fade-in">
              {children}
          </main>
          <div></div>
      </div>
      <Toaster />
      </body>
      </html>
  );
}
